import { RULES_V1 } from "@/core/rules/config.v1";
import { SCRIPTS } from "@/core/scripts";
import { FESTIVAL_DATES } from "@/core/festivals";

// Generates supabase/seed.sql from the typed config so the database and the code can never drift (tests compare them).
const q = (s: string) => `$t$${s}$t$`; // dollar-quoted: scripts contain apostrophes
const arr = (a: string[]) => `array[${a.map(q).join(", ")}]::text[]`;

export function buildSeedSql(): string {
  const out: string[] = [];
  out.push("-- GENERATED by scripts/gen-seed.ts from src/core (do not edit). Idempotent.");

  const v = Number(RULES_V1.version.replace(/\D/g, ""));
  out.push(`insert into rule_versions (version, config, status, approved_by, approved_at, notes) values (${v}, ${q(JSON.stringify(RULES_V1))}::jsonb, 'active', ${q(RULES_V1.approval.approvedBy)}, '${RULES_V1.approval.approvedOn}', ${q("Approved by project owner. Nikhil production sign-off pending.")}) on conflict (version) do nothing;`);

  const texts: string[] = [];
  for (const [key, byLocale] of Object.entries(SCRIPTS))
    for (const [locale, s] of Object.entries(byLocale)) {
      const approved = s.status === "approved" || s.status === "approved_pending_native_check";
      texts.push(`(${q(key)}, '${locale}', ${q(s.text)}, '${s.status}', 1, ${approved ? q("project owner") : "null"}, ${approved ? `'${RULES_V1.approval.approvedOn}'` : "null"})`);
    }
  out.push(`insert into approved_texts (key, locale, body, status, version, approved_by, approved_at) values\n${texts.join(",\n")}\non conflict (key, locale, version) do nothing;`);

  for (const f of FESTIVAL_DATES)
    out.push(`insert into festival_dates (key, names, display, event_date) values (${q(f.key)}, ${arr(f.names)}, ${q(JSON.stringify(f.display))}::jsonb, '${f.date}') on conflict (key) do nothing;`);

  out.push(`insert into vip_referrers (name, notes) values ${RULES_V1.vipReferrers.map((n) => `(${q(n)}, ${q("T05 referrer: flag in the note + notify Nikhil; rules unchanged")})`).join(", ")} on conflict (name) do nothing;`);

  out.push(`delete from studio_hours where holiday_date is null;\ninsert into studio_hours (weekday, opens, closes) values ${[1, 2, 3, 4, 5].map((d) => `(${d}, '10:00', '19:00')`).join(", ")};`);

  const areas = arr(RULES_V1.localities.served);
  const types = arr(["home", "office"]);
  out.push(`insert into designers (name, areas, project_types, is_principal, is_design_lead, active, is_test)
select v.name, ${areas}, ${types}, v.p, v.l, true, true
from (values ('TEST Designer A (principal)', true, false), ('TEST Designer B (design lead)', false, true), ('TEST Designer C', false, false)) as v(name, p, l)
where not exists (select 1 from designers d where d.name = v.name);`);

  return out.join("\n\n") + "\n";
}
